site: 
  title: OpenNMS ALEC Documentation
  url: https://horizon.no42.org
content: 
  sources: 
  - url: https://github.com/indigo423/opennms-docs.git
    branches: HEAD
    tags: v*
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v1.0.1/ui-bundle.zip
asciidoc:
  attributes:
    stem: latexmath
output: 
  clean: true 
  dir: ./public 
  destinations: 
  - provider: fs
  - provider: archive 
